name: Deployment example
on: 
    push:
        branches: ["master","dev"]           

jobs:
    build-and-test:
        runs-on: ubuntu-latest        
        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: Set .Net core SDK 5
              uses: actions/setup-dotnet@v3.0.3
              with:
                dotnet-version: 5.0.x
               
            #  Restore, Build and Test
            - name: Install dependencies
              run : dotnet restore              
                   
            - name: Build
              run: dotnet build              

            - name: Test
              run: dotnet test              

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with: 
                name: archive.zip
                path: /home/runner/work/ToDoTaskApplication/ToDoTaskApplication/bin/Debug/net5.0/
    deploy-dev:
        
        needs: [build-and-test]
        if: github.ref == 'refs/heads/dev'

        runs-on: ubuntu-latest
        environment: 
            name: dev
            url: https://github.com/${{github.repository}}/releases/tag/v${{vars.DEV_VERSION}}
        
        steps:
          - name: Download candidate artifacts
            uses: actions/download-artifact@v3
            with: 
                name: archive.zip
            
          - name: release to dev
            uses: softprops/action-gh-release@v0.1.15
            with: 
                tag_name: v${{vars.DEV_VERSION}}
                token: ${{secrets.DEV_TOKEN}}
                prerelease: true
                draft: true
                name: dev
                files:  v${{vars.DEV_VERSION}}.zip

    deploy-pro:
        needs: [build-and-test]
        if: github.ref == 'refs/heads/master'
        
        runs-on: ubuntu-latest
        environment:
            name: production
            url: https://github.com/${{ github.repository}}/releases/tag/v${{ vars.PROD_VERSION }}
        
        steps: 
           - name: Download candidate artifacts
             uses: actions/download-artifact@v3
             with:
                name: archive.zip

           - name: GH Release
             uses: softprops/action-gh-release@v0.1.15
             with:
                tag_name: v${{ vars.PROD_VERSION }}
                token: ${{ vars.PROD_TOKEN }}
                generate_release_notes: true
                name: Production
                files: v${{ vars.PROD_VERSION }}.zip



                              

