name: Simple Netcore Build
on:
  push:
     branches:
          -master
jobs:
  build: 
   name: Build
   runs-on: ubuntu-latest
   steps:
    - name: Get latest code
      uses: action/checkout@v3
    
    #Setup .NetCore SDk
    - name: Setup .NetCore SDK
      uses: action/setup-dotnet@v3.0.3
      with:
       dotnet-version : 5.0.x

       # Run hello world     
    - run: dotnet --version