name: Verify file

on:
  push:
  pull_request:

jobs:
  verify:
    name: ${{vars.JOB_NAME}}
    if: ${{vars.EXEC_WF == 'true'}}
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - run : |
              echo ${{vars.FILE_TO_CHECK}} update
           #  [[ -f ${{vars.FILE_TO_CHECK}} ]] ||
           # (echo "${{vars.FILE_TO_CHECK}} file needs to be added to ${{github.repository}} !" && exist 1)

